"""Work out a portal's selectors from its rendered results page.

Adding a portal used to mean typing CSS selectors into a form, and the
selectors are the one part nobody can get right by looking at a site from
outside: every portal draws its results in JavaScript. So instead the user
gives a name and the URL of a search they just ran, and this runs on the PC,
against the page as the signed-in browser actually rendered it.

The idea is simple and holds for every job board there is: a results page is
a list of near-identical blocks, each holding one link to one job. Find the
element that repeats the most, with a job-looking link inside each copy, and
that is the card. Everything else is read relative to it.

Pure functions over an HTML string, so it is tested without a browser and the
agent can call it on `page.content()`.
"""
from __future__ import annotations

import re
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from html.parser import HTMLParser
from typing import Any
from urllib.parse import quote, quote_plus

from .generic import slugify

# A card selector needs at least this many copies on the page before it can
# be believed. Three is a nav bar; six is a results list.
MIN_CARDS = 4

# Classes generated by CSS-in-JS or build hashes change on every deploy, so a
# selector built on one dies within weeks. Skip anything that looks minted.
_STABLE_CLASS = re.compile(r"^[A-Za-z_][A-Za-z0-9_-]{1,39}$")
_MINTED = re.compile(r"\d{3,}|[0-9a-f]{6,}|^(css|sc|jss|emotion)-")

_SKIP_TAGS = {"script", "style", "noscript", "svg", "template", "head"}
_HEADINGS = {"h1", "h2", "h3", "h4", "h5"}
_TEXTY = {"span", "div", "p", "li", "small", "em", "strong", "b", "a", "td",
          "h4", "h5", "h6", "label", "time"}

# Which field a class name is hinting at. Checked before falling back to
# document order, because "the second short text after the title" is a guess
# and ".companyName" is not.
_HINTS = (
    ("company", ("comp", "employer", "org", "recruiter")),
    ("location", ("loc", "city", "place", "region", "address")),
    ("salary", ("sal", "ctc", "pay", "compens", "package")),
    ("posted", ("post", "date", "ago", "time", "publish", "day")),
    ("experience", ("exp", "year")),
)


class _El:
    __slots__ = ("tag", "attrs", "parent", "children", "own_text", "order")

    def __init__(self, tag: str, attrs: dict[str, str], parent: "_El | None",
                 order: int) -> None:
        self.tag = tag
        self.attrs = attrs
        self.parent = parent
        self.children: list[_El] = []
        self.own_text: list[str] = []
        self.order = order

    @property
    def classes(self) -> list[str]:
        return [c for c in (self.attrs.get("class") or "").split() if c]

    @property
    def stable_classes(self) -> list[str]:
        return [c for c in self.classes
                if _STABLE_CLASS.match(c) and not _MINTED.search(c)][:2]

    def text(self) -> str:
        parts = list(self.own_text)
        for child in self.children:
            parts.append(child.text())
        return re.sub(r"\s+", " ", " ".join(parts)).strip()

    def own(self) -> str:
        return re.sub(r"\s+", " ", " ".join(self.own_text)).strip()

    def walk(self):
        for child in self.children:
            yield child
            yield from child.walk()

    def ancestors(self, levels: int):
        node, n = self.parent, 0
        while node is not None and n < levels:
            yield node
            node, n = node.parent, n + 1

    def selector(self) -> str | None:
        stable = self.stable_classes
        if stable:
            return self.tag + "".join(f".{c}" for c in stable)
        if self.tag in ("li", "article", "tr"):
            return self.tag
        return None


class _Tree(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.root = _El("root", {}, None, 0)
        self._stack = [self.root]
        self._skip = 0
        self._order = 0

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag in _SKIP_TAGS:
            self._skip += 1
            return
        if self._skip:
            return
        self._order += 1
        el = _El(tag, {k: (v or "") for k, v in attrs}, self._stack[-1], self._order)
        self._stack[-1].children.append(el)
        if tag not in ("br", "img", "input", "hr", "meta", "link"):
            self._stack.append(el)

    def handle_endtag(self, tag: str) -> None:
        if tag in _SKIP_TAGS:
            self._skip = max(0, self._skip - 1)
            return
        if self._skip:
            return
        for i in range(len(self._stack) - 1, 0, -1):
            if self._stack[i].tag == tag:
                del self._stack[i:]
                return

    def handle_data(self, data: str) -> None:
        if not self._skip and data.strip():
            self._stack[-1].own_text.append(data)


def _parse(html: str) -> _El:
    tree = _Tree()
    tree.feed(html or "")
    return tree.root


@dataclass
class Detection:
    result_card: str
    title: str
    link: str
    cards: int
    company: str = ""
    location: str = ""
    salary: str = ""
    posted: str = ""
    experience: str = ""
    href_prefix: str = ""
    notes: list[str] = field(default_factory=list)

    def to_search(self) -> dict[str, Any]:
        fields: dict[str, Any] = {"title": self.title,
                                  "url": {"selector": self.link, "attr": "href"}}
        for name in ("company", "location", "salary", "posted", "experience"):
            if getattr(self, name):
                fields[name] = getattr(self, name)
        return {"result_card": self.result_card, "fields": fields}


def _job_anchors(root: _El) -> list[_El]:
    out = []
    for el in root.walk():
        if el.tag != "a":
            continue
        href = el.attrs.get("href", "")
        if not href or href.startswith(("#", "javascript:", "mailto:", "tel:")):
            continue
        if 8 <= len(el.text()) <= 150:
            out.append(el)
    return out


def _texty_count(el: _El) -> int:
    """Distinct short texts inside an element -- what makes a card a card."""
    n = 0
    for x in el.walk():
        if x.tag in _TEXTY and 2 <= len(x.own()) <= 150:
            n += 1
    return n


def _common_href_prefix(anchors: list[_El]) -> str:
    paths = []
    for a in anchors:
        href = a.attrs.get("href", "")
        href = re.sub(r"^https?://[^/]+", "", href).split("?")[0]
        paths.append([seg for seg in href.split("/") if seg])
    if not paths:
        return ""
    prefix: list[str] = []
    for segs in zip(*paths):
        if len(set(segs)) == 1 and not re.search(r"\d", segs[0]):
            prefix.append(segs[0])
        else:
            break
    return "/" + "/".join(prefix) + "/" if prefix else ""


def _title_selector(anchors: list[_El], href_prefix: str) -> str:
    """The most specific selector the title links share."""
    own = Counter(a.selector() for a in anchors if a.stable_classes)
    if own and own.most_common(1)[0][1] >= len(anchors) * 0.6:
        return own.most_common(1)[0][0]
    parents = Counter()
    for a in anchors:
        p = a.parent
        if p is not None and p.tag in _HEADINGS:
            parents[(p.selector() or p.tag) + " a"] += 1
    if parents and parents.most_common(1)[0][1] >= len(anchors) * 0.6:
        return parents.most_common(1)[0][0]
    if href_prefix and href_prefix != "/":
        return f'a[href*="{href_prefix}"]'
    return "a"


def _guess_fields(cards: list[_El], title_anchor: dict[int, _El]) -> dict[str, str]:
    """Short texts that appear in most cards, by class. Hints first, then
    document order -- company then location is how every board lays it out."""
    per_class: dict[str, list[int]] = defaultdict(list)
    seen_in: Counter = Counter()
    for card in cards:
        title = title_anchor.get(id(card))
        skip = {id(title)} | {id(x) for x in (title.ancestors(3) if title else [])}
        found: dict[str, int] = {}
        for el in card.walk():
            if id(el) in skip or el.tag not in _TEXTY or not el.stable_classes:
                continue
            text = el.own()
            if not (2 <= len(text) <= 60):
                continue
            sel = el.selector()
            if sel and sel not in found:
                found[sel] = el.order - card.order
        for sel, pos in found.items():
            per_class[sel].append(pos)
            seen_in[sel] += 1

    common = [sel for sel, n in seen_in.items() if n >= max(2, len(cards) * 0.6)]
    common.sort(key=lambda s: sorted(per_class[s])[len(per_class[s]) // 2])

    out: dict[str, str] = {}
    for sel in list(common):
        low = sel.lower()
        for name, hints in _HINTS:
            if name not in out and any(h in low for h in hints):
                out[name] = sel
                common.remove(sel)
                break
    for name in ("company", "location"):
        if name not in out and common:
            out[name] = common.pop(0)
    return out


def detect(html: str) -> Detection | None:
    """The card, the title link, and the fields around them -- or None if the
    page has no repeating block with a job link in it."""
    root = _parse(html)
    anchors = _job_anchors(root)
    if len(anchors) < MIN_CARDS:
        return None

    # For every anchor and each of its ancestors, how many *distinct* ancestor
    # elements share a signature. The repeated one is the card.
    members: dict[tuple, dict[int, _El]] = defaultdict(dict)
    anchor_of: dict[tuple, dict[int, _El]] = defaultdict(dict)
    for a in anchors:
        for depth, anc in enumerate(a.ancestors(5)):
            sel = anc.selector()
            if not sel:
                continue
            key = (sel, depth)
            members[key][id(anc)] = anc
            anchor_of[key].setdefault(id(anc), a)

    anchor_ids = {id(a) for a in anchors}
    best: tuple | None = None
    for key, elems in members.items():
        n = len(elems)
        if n < MIN_CARDS:
            continue
        # Cards hold one job each; a wrapper holding many is the list, not
        # the card.
        anchors_inside = sum(1 for e in elems.values()
                             for x in e.walk() if id(x) in anchor_ids)
        if anchors_inside > n * 3:
            continue
        # A card is rich: a title *and* something else -- company, city,
        # a date. The heading wrapped around each title repeats exactly as
        # often as the card does, and a sidebar of five links repeats too;
        # neither holds a second text, so neither is a card.
        rich = sum(1 for e in elems.values() if _texty_count(e) >= 2)
        if rich < n * 0.6:
            continue
        # Among rich repeats prefer the outermost: it holds everything the
        # inner one does and the fields around it too.
        score = (n, key[1])
        if best is None or score > best[0]:
            best = (score, key)
    if best is None:
        return None

    sel, depth = best[1]
    cards = list(members[(sel, depth)].values())
    title_anchor = anchor_of[(sel, depth)]
    titles = [title_anchor[id(c)] for c in cards if id(c) in title_anchor]
    prefix = _common_href_prefix(titles)
    title_sel = _title_selector(titles, prefix)

    det = Detection(result_card=sel, title=title_sel, link=title_sel,
                    cards=len(cards), href_prefix=prefix)
    for name, value in _guess_fields(cards, title_anchor).items():
        setattr(det, name, value)
    if not det.company:
        det.notes.append("could not tell which text is the company")
    if not det.location:
        det.notes.append("could not tell which text is the location")
    return det


# ------------------------------------------------------------ the URL
def _variants(text: str) -> list[str]:
    t = text.strip()
    if not t:
        return []
    forms = [quote_plus(t), quote(t), t, t.replace(" ", "-"), t.replace(" ", "+"),
             slugify(t), t.replace(" ", "")]
    seen: list[str] = []
    for f in forms:
        if f and f.lower() not in {s.lower() for s in seen}:
            seen.append(f)
    return sorted(seen, key=len, reverse=True)


def tokenise_search_url(url: str, role: str, location: str) -> tuple[str, list[str]]:
    """Replace the role and city the user typed with the tokens the search
    template understands. Returns the template and which tokens were placed.

    A hyphenated form inside the path becomes the slug token; anything else
    becomes the encoded one. Case-insensitive, longest form first, so
    "qa+automation" is not left half-replaced by "qa".
    """
    out = url
    placed: list[str] = []
    for text, enc_token, slug_token in ((role, "{keywords}", "{role_slug}"),
                                        (location, "{location}", "{location_slug}")):
        for form in _variants(text):
            pattern = re.compile(re.escape(form), re.IGNORECASE)
            if not pattern.search(out):
                continue
            token = slug_token if ("-" in form and " " not in form
                                   and form.lower() == slugify(text)) else enc_token
            out = pattern.sub(token, out, count=1)
            placed.append(token)
            break
    return out, placed


def definition_from(name: str, url: str, template: str,
                    det: Detection | None, marker: str = "") -> dict[str, Any]:
    """The mapping a custom portal holds, built from what was detected."""
    origin = re.match(r"^(https?://[^/]+)", url)
    out: dict[str, Any] = {
        "name": name,
        "base_url": origin.group(1) if origin else url,
        "auth": {"mode": "persistent_profile"},
        "search": {"url_template": template,
                   "pagination": {"max_pages": 3}},
    }
    if marker:
        out["auth"]["logged_in_selector"] = marker
    if det is not None:
        out["search"].update(det.to_search())
    return out
