"""Work out a portal's selectors from its rendered results page.

Adding a portal used to mean typing CSS selectors into a form, and the
selectors are the one part nobody can get right by looking at a site from
outside: every portal draws its results in JavaScript. So instead the user
gives a name and the URL of a search they just ran, and this runs on the PC,
against the page as the signed-in browser actually rendered it.

The idea is simple and holds for every job board there is: a results page is
a list of near-identical blocks, each holding one link to one job. Find the
element that repeats the most, with a job-looking link inside each copy, and
that is the card. Everything else is read relative to it.

Pure functions over an HTML string, so it is tested without a browser and the
agent can call it on `page.content()`.
"""
from __future__ import annotations

import re
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from html.parser import HTMLParser
from typing import Any
from urllib.parse import quote, quote_plus

from .generic import slugify

# A card selector needs at least this many copies on the page before it can
# be believed. Three is a nav bar; six is a results list.
MIN_CARDS = 4

# Classes generated by CSS-in-JS or build hashes change on every deploy, so a
# selector built on one dies within weeks. Skip anything that looks minted.
_STABLE_CLASS = re.compile(r"^[A-Za-z_][A-Za-z0-9_-]{1,39}$")
# Minted names come in more shapes than a hex run: Material-UI's
# `mui-style-1yuhvjn`, CSS-modules' `card__x7f3ab`, anything ending in a
# dash or underscore followed by a digit and a few more characters. Hirist
# is a MUI app and the first pass kept `mui-style-1yuhvjn` as a card
# selector -- correct for a week, dead on the next deploy.
_MINTED = re.compile(
    r"\d{3,}|[0-9a-f]{6,}|^(css|sc|jss|emotion|mui-style|chakra)-"
    r"|[-_]\d[a-z0-9]{3,}$|__[a-z0-9]*\d[a-z0-9]*$")
# Attributes put there for tests to find things by. Stable by intent, which
# is more than any class can promise.
_TEST_ATTRS = ("data-testid", "data-test", "data-qa", "data-cy", "data-automation")

_SKIP_TAGS = {"script", "style", "noscript", "svg", "template", "head"}
_HEADINGS = {"h1", "h2", "h3", "h4", "h5"}
_TEXTY = {"span", "div", "p", "li", "small", "em", "strong", "b", "a", "td",
          "h4", "h5", "h6", "label", "time"}

# Which field a class name is hinting at. Checked before falling back to
# document order, because "the second short text after the title" is a guess
# and ".companyName" is not.
_HINTS = (
    ("company", ("comp", "employer", "org", "recruiter")),
    ("location", ("loc", "city", "place", "region", "address")),
    ("salary", ("sal", "ctc", "pay", "compens", "package")),
    ("posted", ("post", "date", "ago", "time", "publish", "day")),
    ("experience", ("exp", "year")),
)


class _El:
    __slots__ = ("tag", "attrs", "parent", "children", "own_text", "order")

    def __init__(self, tag: str, attrs: dict[str, str], parent: "_El | None",
                 order: int) -> None:
        self.tag = tag
        self.attrs = attrs
        self.parent = parent
        self.children: list[_El] = []
        self.own_text: list[str] = []
        self.order = order

    @property
    def classes(self) -> list[str]:
        return [c for c in (self.attrs.get("class") or "").split() if c]

    @property
    def stable_classes(self) -> list[str]:
        return [c for c in self.classes
                if _STABLE_CLASS.match(c) and not _MINTED.search(c)][:2]

    def text(self) -> str:
        parts = list(self.own_text)
        for child in self.children:
            parts.append(child.text())
        return re.sub(r"\s+", " ", " ".join(parts)).strip()

    def own(self) -> str:
        return re.sub(r"\s+", " ", " ".join(self.own_text)).strip()

    def walk(self):
        for child in self.children:
            yield child
            yield from child.walk()

    def ancestors(self, levels: int):
        node, n = self.parent, 0
        while node is not None and n < levels:
            yield node
            node, n = node.parent, n + 1

    def selector(self) -> str | None:
        for attr in _TEST_ATTRS:
            value = self.attrs.get(attr, "")
            if value and '"' not in value and not _MINTED.search(value):
                return f'{self.tag}[{attr}="{value}"]'
        stable = self.stable_classes
        if stable:
            return self.tag + "".join(f".{c}" for c in stable)
        role = self.attrs.get("role", "")
        if role in ("listitem", "article", "row"):
            return f'{self.tag}[role="{role}"]'
        if self.tag in ("li", "article", "tr"):
            return self.tag
        return None


class _Tree(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.root = _El("root", {}, None, 0)
        self._stack = [self.root]
        self._skip = 0
        self._order = 0

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag in _SKIP_TAGS:
            self._skip += 1
            return
        if self._skip:
            return
        self._order += 1
        el = _El(tag, {k: (v or "") for k, v in attrs}, self._stack[-1], self._order)
        self._stack[-1].children.append(el)
        if tag not in ("br", "img", "input", "hr", "meta", "link"):
            self._stack.append(el)

    def handle_endtag(self, tag: str) -> None:
        if tag in _SKIP_TAGS:
            self._skip = max(0, self._skip - 1)
            return
        if self._skip:
            return
        for i in range(len(self._stack) - 1, 0, -1):
            if self._stack[i].tag == tag:
                del self._stack[i:]
                return

    def handle_data(self, data: str) -> None:
        if not self._skip and data.strip():
            self._stack[-1].own_text.append(data)


def _parse(html: str) -> _El:
    tree = _Tree()
    tree.feed(html or "")
    return tree.root


@dataclass
class Detection:
    result_card: str
    title: str
    link: str
    cards: int
    company: str = ""
    location: str = ""
    salary: str = ""
    posted: str = ""
    experience: str = ""
    href_prefix: str = ""
    notes: list[str] = field(default_factory=list)

    def to_search(self) -> dict[str, Any]:
        fields: dict[str, Any] = {"title": self.title,
                                  "url": {"selector": self.link, "attr": "href"}}
        for name in ("company", "location", "salary", "posted", "experience"):
            if getattr(self, name):
                fields[name] = getattr(self, name)
        return {"result_card": self.result_card, "fields": fields}


def _job_anchors(root: _El) -> list[_El]:
    out = []
    for el in root.walk():
        if el.tag != "a":
            continue
        href = el.attrs.get("href", "")
        if not href or href.startswith(("#", "javascript:", "mailto:", "tel:")):
            continue
        if 8 <= len(el.text()) <= 150:
            out.append(el)
    return out


def _texty_count(el: _El) -> int:
    """Distinct short texts inside an element -- what makes a card a card."""
    n = 0
    for x in el.walk():
        if x.tag in _TEXTY and 2 <= len(x.own()) <= 150:
            n += 1
    return n


def _common_href_prefix(anchors: list[_El]) -> str:
    paths = []
    for a in anchors:
        href = a.attrs.get("href", "")
        href = re.sub(r"^https?://[^/]+", "", href).split("?")[0]
        paths.append([seg for seg in href.split("/") if seg])
    if not paths:
        return ""
    prefix: list[str] = []
    for segs in zip(*paths):
        if len(set(segs)) == 1 and not re.search(r"\d", segs[0]):
            prefix.append(segs[0])
        else:
            break
    return "/" + "/".join(prefix) + "/" if prefix else ""


def _title_selector(anchors: list[_El], href_prefix: str) -> str:
    """The most specific selector the title links share."""
    own = Counter(a.selector() for a in anchors if a.stable_classes)
    if own and own.most_common(1)[0][1] >= len(anchors) * 0.6:
        return own.most_common(1)[0][0]
    parents = Counter()
    for a in anchors:
        p = a.parent
        if p is not None and p.tag in _HEADINGS:
            parents[(p.selector() or p.tag) + " a"] += 1
    if parents and parents.most_common(1)[0][1] >= len(anchors) * 0.6:
        return parents.most_common(1)[0][0]
    if href_prefix and href_prefix != "/":
        return f'a[href*="{href_prefix}"]'
    return "a"


def _guess_fields(cards: list[_El], title_anchor: dict[int, _El]) -> dict[str, str]:
    """Short texts that appear in most cards, by class. Hints first, then
    document order -- company then location is how every board lays it out."""
    per_class: dict[str, list[int]] = defaultdict(list)
    seen_in: Counter = Counter()
    for card in cards:
        title = title_anchor.get(id(card))
        skip = {id(title)} | {id(x) for x in (title.ancestors(3) if title else [])}
        found: dict[str, int] = {}
        for el in card.walk():
            if id(el) in skip or el.tag not in _TEXTY or not el.stable_classes:
                continue
            text = el.own()
            if not (2 <= len(text) <= 60):
                continue
            sel = el.selector()
            if sel and sel not in found:
                found[sel] = el.order - card.order
        for sel, pos in found.items():
            per_class[sel].append(pos)
            seen_in[sel] += 1

    common = [sel for sel, n in seen_in.items() if n >= max(2, len(cards) * 0.6)]
    common.sort(key=lambda s: sorted(per_class[s])[len(per_class[s]) // 2])

    out: dict[str, str] = {}
    for sel in list(common):
        low = sel.lower()
        for name, hints in _HINTS:
            if name not in out and any(h in low for h in hints):
                out[name] = sel
                common.remove(sel)
                break
    for name in ("company", "location"):
        if name not in out and common:
            out[name] = common.pop(0)
    return out


def detect(html: str) -> Detection | None:
    """The card, the title link, and the fields around them -- or None if the
    page has no repeating block with a job link in it."""
    root = _parse(html)
    anchors = _job_anchors(root)
    if len(anchors) < MIN_CARDS:
        return None

    # For every anchor and each of its ancestors, how many *distinct* ancestor
    # elements share a signature. The repeated one is the card.
    members: dict[tuple, dict[int, _El]] = defaultdict(dict)
    anchor_of: dict[tuple, dict[int, _El]] = defaultdict(dict)
    for a in anchors:
        for depth, anc in enumerate(a.ancestors(5)):
            sel = anc.selector()
            if not sel:
                continue
            key = (sel, depth)
            members[key][id(anc)] = anc
            anchor_of[key].setdefault(id(anc), a)

    anchor_ids = {id(a) for a in anchors}
    best: tuple | None = None
    for key, elems in members.items():
        n = len(elems)
        if n < MIN_CARDS:
            continue
        # Cards hold one job each; a wrapper holding many is the list, not
        # the card.
        anchors_inside = sum(1 for e in elems.values()
                             for x in e.walk() if id(x) in anchor_ids)
        if anchors_inside > n * 3:
            continue
        # A card is rich: a title *and* something else -- company, city,
        # a date. The heading wrapped around each title repeats exactly as
        # often as the card does, and a sidebar of five links repeats too;
        # neither holds a second text, so neither is a card.
        rich = sum(1 for e in elems.values() if _texty_count(e) >= 2)
        if rich < n * 0.6:
            continue
        # Among rich repeats prefer the outermost: it holds everything the
        # inner one does and the fields around it too.
        score = (n, key[1])
        if best is None or score > best[0]:
            best = (score, key)
    if best is None:
        return None

    sel, depth = best[1]
    cards = list(members[(sel, depth)].values())
    title_anchor = anchor_of[(sel, depth)]
    titles = [title_anchor[id(c)] for c in cards if id(c) in title_anchor]
    prefix = _common_href_prefix(titles)
    title_sel = _title_selector(titles, prefix)

    # A card whose only stable class is something like MuiBox-root matches
    # every box on the page, not the fifteen that are cards. Narrow it to
    # the ones holding a title link. Ancestors still match; the scraper
    # drops the duplicates that produces.
    on_page = sum(1 for e in root.walk() if e.selector() == sel)
    if on_page > len(cards) * 1.5:
        sel = f"{sel}:has({title_sel})"

    det = Detection(result_card=sel, title=title_sel, link=title_sel,
                    cards=len(cards), href_prefix=prefix)
    for name, value in _guess_fields(cards, title_anchor).items():
        setattr(det, name, value)
    if not det.company:
        det.notes.append("could not tell which text is the company")
    if not det.location:
        det.notes.append("could not tell which text is the location")
    return det


# ---------------------------------------------------- finding the way in
# Given only a site's front door, the app has to do what a person does on a
# board they have never seen: notice whether they are signed in, find the
# search box, type a role and a city, and read the page that comes back.
# The three functions below are the noticing; the agent does the typing.

_KEYWORD_HINTS = ("keyword", "skill", "designation", "title", "role", "job",
                  "search", "query", "what", "term", "position", "profile")
_KEYWORD_NAMES = {"q", "k", "kw", "key", "keyword", "keywords", "query", "what",
                  "search", "s", "job", "jobs", "txt", "text"}
_LOCATION_HINTS = ("location", "city", "where", "place", "region", "area",
                   "locality")
_LOCATION_NAMES = {"l", "loc", "location", "locations", "where", "city", "cities",
                   "place"}
_NOT_A_SEARCH_INPUT = {"hidden", "password", "email", "checkbox", "radio",
                       "submit", "button", "file", "tel", "number", "date"}
_SUBMIT_WORDS = ("search", "find", "go", "submit", "show")

_LOGIN_HREF = re.compile(r"(login|signin|sign-in|log-in|/auth\b)", re.IGNORECASE)
_SIGNED_IN_MARK = re.compile(
    r"(logout|log-out|signout|sign-out|/my-?profile|/my-?account|/candidate/(?:home|dashboard|profile)|"
    r">\s*(?:log\s?out|sign\s?out|my profile|my account)\s*<)", re.IGNORECASE)
_NOT_A_JOBS_LINK = ("login", "signin", "employer", "recruiter", "post-a-job",
                    "post-job", "hire", "pricing", "blog", "career-advice")


@dataclass
class SearchForm:
    keyword: str
    location: str = ""
    submit: str = ""          # empty: press Enter in the keyword box


def _hint_score(el: _El, hints: tuple[str, ...], names: set[str]) -> int:
    attrs = el.attrs
    name = (attrs.get("name") or "").strip().lower()
    ident = (attrs.get("id") or "").strip().lower()
    if name in names or ident in names:
        return 3
    blob = " ".join(attrs.get(k, "") for k in
                    ("name", "id", "placeholder", "aria-label", "class", "title")).lower()
    return sum(1 for h in hints if h in blob)


def _input_selector(el: _El) -> str:
    ident = el.attrs.get("id", "")
    if ident and _STABLE_CLASS.match(ident) and not _MINTED.search(ident):
        return f"#{ident}"
    for attr in ("name", "placeholder", "aria-label"):
        value = el.attrs.get(attr, "")
        if value and '"' not in value:
            return f'{el.tag}[{attr}="{value}"]'
    kind = el.attrs.get("type", "")
    return f'{el.tag}[type="{kind}"]' if kind else el.tag


def _text_inputs(scope: _El) -> list[_El]:
    out = []
    for el in scope.walk():
        if el.tag not in ("input", "textarea"):
            continue
        if (el.attrs.get("type") or "text").lower() in _NOT_A_SEARCH_INPUT:
            continue
        out.append(el)
    return out


def _submit_selector(scope: _El) -> str:
    for el in scope.walk():
        if el.tag == "button" and (el.attrs.get("type") or "").lower() == "submit":
            return _input_selector(el) if el.attrs.get("id") else 'button[type="submit"]'
        if el.tag == "input" and (el.attrs.get("type") or "").lower() == "submit":
            return 'input[type="submit"]'
    # A <button> with no type attribute submits its form too, but the CSS
    # button[type="submit"] does not match it -- there is no attribute to
    # match. Reach it by what it says instead.
    for el in scope.walk():
        if el.tag in ("button", "a"):
            label = (el.text() or el.attrs.get("aria-label", "")).strip()
            if label and any(w == label.lower() or w in label.lower().split()
                             for w in _SUBMIT_WORDS) and '"' not in label:
                return f'{el.tag}:has-text("{label}")'
    return ""


def find_search_form(html: str) -> SearchForm | None:
    """The site's job-search box: a text input that means "keyword", with an
    optional one that means "location", and how to submit them.

    Forms first, because a real <form> keeps the two inputs together. A
    board built as an app often has no form at all, so the page as a whole
    is the last candidate. A form holding a password field is a login form,
    whatever its other inputs are called.
    """
    root = _parse(html)
    scopes = [f for f in root.walk() if f.tag == "form"] + [root]
    best: tuple[int, SearchForm] | None = None
    for scope in scopes:
        inputs = _text_inputs(scope)
        if not inputs or any((i.attrs.get("type") or "").lower() == "password"
                             for i in scope.walk() if i.tag == "input"):
            continue
        keyword = max(inputs, key=lambda i: _hint_score(i, _KEYWORD_HINTS, _KEYWORD_NAMES))
        kscore = _hint_score(keyword, _KEYWORD_HINTS, _KEYWORD_NAMES)
        if kscore == 0:
            continue
        others = [i for i in inputs if i is not keyword]
        location = max(others, key=lambda i: _hint_score(i, _LOCATION_HINTS, _LOCATION_NAMES),
                       default=None)
        lscore = (_hint_score(location, _LOCATION_HINTS, _LOCATION_NAMES)
                  if location is not None else 0)
        form = SearchForm(keyword=_input_selector(keyword),
                          location=_input_selector(location) if lscore else "",
                          submit=_submit_selector(scope))
        score = kscore * 2 + lscore + (1 if scope.tag == "form" else 0)
        if best is None or score > best[0]:
            best = (score, form)
    return best[1] if best else None


def _absolute(href: str, origin: str) -> str:
    if href.startswith("http"):
        return href
    if href.startswith("//"):
        return "https:" + href
    if href.startswith("/"):
        return origin.rstrip("/") + href
    return ""


def find_jobs_link(html: str, origin: str) -> str:
    """A link from the front door to wherever the searching happens."""
    root = _parse(html)
    best: tuple[int, str] | None = None
    for el in root.walk():
        if el.tag != "a":
            continue
        href = el.attrs.get("href", "")
        low = href.lower()
        if not href or any(bad in low for bad in _NOT_A_JOBS_LINK):
            continue
        text = el.text().lower()
        score = 0
        if "search" in low:
            score += 2
        if "/jobs" in low or "/job-search" in low or low.endswith("/jobs/"):
            score += 2
        if "search jobs" in text or "find jobs" in text or "browse jobs" in text:
            score += 2
        elif "job" in text:
            score += 1
        if score and (best is None or score > best[0]):
            url = _absolute(href, origin)
            if url:
                best = (score, url)
    return best[1] if best else ""


def find_login_link(html: str, origin: str) -> str:
    """The first sign-in link on the page, made absolute."""
    root = _parse(html)
    for el in root.walk():
        if el.tag != "a":
            continue
        href = el.attrs.get("href", "")
        if href and _LOGIN_HREF.search(href) and "logout" not in href.lower():
            url = _absolute(href, origin)
            if url:
                return url
    return ""


def looks_signed_out(html: str) -> bool:
    """A sign-in link and nothing that only a signed-in page shows."""
    if not html:
        return False
    has_login = bool(find_login_link(html, "https://x"))
    return has_login and not _SIGNED_IN_MARK.search(html)


# ------------------------------------------------------ the apply button
# Labels that mean "apply to this job". Checked as whole labels first, then
# as a prefix, then anywhere -- "Apply Now" beats a link that merely mentions
# applying somewhere in a sentence.
_APPLY_EXACT = ("apply", "apply now", "easy apply", "quick apply", "apply for this job",
                "apply on company site", "apply on company website", "i'm interested")
# Labels that contain "apply" and are not the button: a state, a count, a
# filter control, a re-application.
_NOT_APPLY = ("applied", "application", "filter", "reapply", "re-apply", "apply to all",
              "apply for jobs", "how to apply")


def find_apply_button(html: str) -> str:
    """The button that applies to the job on this page, as a selector.

    Written for the case the shipped selector was guessed and the site
    renders something else: find the control whose label says apply, and
    reach it by a test id or id if it has one, otherwise by its exact label.
    Exact, because "Apply filters" and "Applied" also contain the word.
    """
    root = _parse(html)
    best: tuple[int, _El, str] | None = None
    for el in root.walk():
        is_button = el.tag in ("button", "a", "input") or el.attrs.get("role") == "button"
        if not is_button:
            continue
        if el.tag == "input":
            if (el.attrs.get("type") or "").lower() not in ("submit", "button"):
                continue
            label = el.attrs.get("value", "")
        else:
            label = el.text() or el.attrs.get("aria-label", "") or el.attrs.get("title", "")
        label = re.sub(r"\s+", " ", label).strip()
        low = label.lower()
        if not low or len(low) > 40 or "apply" not in low:
            continue
        if any(bad in low for bad in _NOT_APPLY):
            continue
        score = 4 if low in _APPLY_EXACT else (3 if low.startswith("apply") else 1)
        if el.tag == "button":
            score += 1
        if best is None or score > best[0]:
            best = (score, el, label)
    if best is None:
        return ""

    _, el, label = best
    for attr in _TEST_ATTRS:
        value = el.attrs.get(attr, "")
        if value and '"' not in value and not _MINTED.search(value):
            return f'{el.tag}[{attr}="{value}"]'
    ident = el.attrs.get("id", "")
    if ident and _STABLE_CLASS.match(ident) and not _MINTED.search(ident):
        return f"#{ident}"
    if el.tag == "input":
        return f'input[value="{label}"]' if '"' not in label else 'input[type="submit"]'
    tag = el.tag if el.tag in ("button", "a") else f'{el.tag}[role="button"]'
    if '"' not in label:
        # :text-is matches the whole label, whitespace-normalised, so "Apply"
        # does not also mean "Apply filters" further down the page.
        return f'{tag}:text-is("{label}")'
    stable = el.stable_classes
    return tag + "".join(f".{c}" for c in stable) if stable else tag


# ------------------------------------------------------------ the URL
def _variants(text: str) -> list[str]:
    t = text.strip()
    if not t:
        return []
    forms = [quote_plus(t), quote(t), t, t.replace(" ", "-"), t.replace(" ", "+"),
             slugify(t), t.replace(" ", "")]
    seen: list[str] = []
    for f in forms:
        if f and f.lower() not in {s.lower() for s in seen}:
            seen.append(f)
    return sorted(seen, key=len, reverse=True)


def tokenise_search_url(url: str, role: str, location: str) -> tuple[str, list[str]]:
    """Replace the role and city the user typed with the tokens the search
    template understands. Returns the template and which tokens were placed.

    A hyphenated form inside the path becomes the slug token; anything else
    becomes the encoded one. Case-insensitive, longest form first, so
    "qa+automation" is not left half-replaced by "qa".
    """
    out = url
    placed: list[str] = []
    for text, enc_token, slug_token in ((role, "{keywords}", "{role_slug}"),
                                        (location, "{location}", "{location_slug}")):
        for form in _variants(text):
            pattern = re.compile(re.escape(form), re.IGNORECASE)
            if not pattern.search(out):
                continue
            token = slug_token if ("-" in form and " " not in form
                                   and form.lower() == slugify(text)) else enc_token
            out = pattern.sub(token, out, count=1)
            placed.append(token)
            break
    return out, placed


def definition_from(name: str, url: str, template: str,
                    det: Detection | None, marker: str = "") -> dict[str, Any]:
    """The mapping a custom portal holds, built from what was detected."""
    origin = re.match(r"^(https?://[^/]+)", url)
    out: dict[str, Any] = {
        "name": name,
        "base_url": origin.group(1) if origin else url,
        "auth": {"mode": "persistent_profile"},
        "search": {"url_template": template,
                   "pagination": {"max_pages": 3}},
    }
    if marker:
        out["auth"]["logged_in_selector"] = marker
    if det is not None:
        out["search"].update(det.to_search())
    return out
